import { Product, ProductItem } from './types';

export const IMAGES = {
    heroWoman: "https://lh3.googleusercontent.com/aida-public/AB6AXuDMioKkTJDy1eWCtSjx9bR281ocyVdbQEPRpfmP2txtBBnD_sYMsBwgCJLDTzuMAlus9_V_RjnY2bLeb7RE1Eiow3ByDpLclijb4rj8vNK123AC-sPhotwnid-hcRpYN1uMU4TI92A2JtwPtKWWfhIbKEB-6bdU5FfXCRoYSrkSs3m0H4FHLbjNV1JydI9gI84J2KD0OHM_7VOZ0BtxhJKBJXaNtXDWZfmyVgvMKPTgMHEdh7XuB40DqQKJ2kfThO2s-hbJjC7h1Qg",
    textureBeige: "https://lh3.googleusercontent.com/aida-public/AB6AXuAwL27ofCdm7pSmx69JThw6lfdCVqR89-7IPNvsQIon46M3ip2FZoZQBHlIuX0RXJM60d8UzibXySjeexfKqJB5joJlzW-92vD3eRLtqf4iF1PwFYZKhOtZp4THDYIvfaQuFjgUpWqmQronlUNiGDZBp2h2zE-6kpGWlskE99AVo9HaB6MJtg_McP3YGu0IXpKH8CPkH_3jChoWgC8qVkI3Y-U2clBDGjuzPmmppP_WR61oV7sq5JMIgdFpniBPBKI39tay1VUV2R0",
    heroWomanMobile: "https://lh3.googleusercontent.com/aida-public/AB6AXuBEHLvngErKpLdOmxALjbsQahXQqoMI9iQEGs0QSWbf4ObMATQnha14QVD_d3rvpidg_w7xKWvZpyqhV980k2MDZeR_JlIqhNvRzja4iFUIGz8mne2qWavNM5h2gC2wHHnlUHHz6qJerF4K5G28Rvq0OfgVx53hJczd41DJd2V9dcnzxhJdfb0jhE7QBmfrKWNZErRI4xR2RVm_TLeRwL8zHjKHBosEYtDYVxwnx8VFPBlxxpCL9ISWAxdP-TEZKvUUcHaG8ru0xq0",
    linenShirt: "https://lh3.googleusercontent.com/aida-public/AB6AXuAdXTnNgEg7m5-La9e2vE1PLvR0WNExuBqV-GXydFW8Mlju4MPB5dHbtUMaH_O3AutRLkZagtXQ48C6w4Fg4WfMUuEeiRJk-QkbnnNRWh0r8YbOlyQnQJSon4uS6jpjEgGKSEHxubro90RTmVtoLEacd0_ORMlZEhqau6A9DuwS8USayibEikRKoXfEbGU8lBB4dneae_d4Yo59FcPm8GZVZ_a-DY6y3k5hSMoHPAijRw0Ee1S8eMtWxTyoLmi4tXMcq6RixyDQ4L4",
    blazerOversized: "https://lh3.googleusercontent.com/aida-public/AB6AXuAJ0M07YgVdj-G6eDP3VkqKNyyA6Bv4fwvqcT_Lyq8whyJPQOAhHfoK-jpUibo_ZfXlRSS45h9plNAX0UiwNJNtIbNWobAeGRHkSR8hO9oDvzmYoUYDmf1ixoSLSHhNhfjfc5N8HRPPvI1OpBDnH3r4ba5ax02FPOtR7pDqu7fFNdjAImY7vKQqtqUMn_9G14ptQo9_AhqU0un0d1q5cAJFOjXWXUR_DYs1c1myMaM5GOh1HETCbAgq39vjiPMHSeBf6EJO5UXYW6U",
    denimJacket: "https://lh3.googleusercontent.com/aida-public/AB6AXuC-hGBE2Ji3b1WU1ATaaC5Yl_DnFnJ_m285TA1qMNpRUwEwNMOBvQKjaK1u8iszDYa3ScUd7liwhNfaDrTU5oZmKgwjUY3kwlVOcUFqJKmqeUTqyWfXT9WVs3PB4IFvsu0fwgCMD3tpECfqVPxQ4WpwwxL3fdZcNzM8AzQeUo5IiVLkL3h4cFpkdR35OXELaR9u2lFjsJB68F3zn2vJTRpK7G1BdODixiKFd8Q92WT1vPJUhEEQVn7pxzkUZzwTIzNTjkj-66-12Gg",
    silkBlouse: "https://lh3.googleusercontent.com/aida-public/AB6AXuAGXi0d_vNN_IEwotPDIjDEFUOJbiUlNufVqVxZLpVMPQktvAe_9iwM5u0GpWSNB3-90-tpBVGlmREyaADqpwqKrU839lm15KqPgteO1hDoaotvG4LZwtZCiPVsJDez-UkGWj2uem0tQsLSWHFHHogU3hlGGfaCq_pQeMOVbQjBXdzFjqrY2xYe5gMJn4RNl4mclGD1B8srko65VeFbXQ2QfJ6UruAkl4SSE_Y4BIolb-2_WbAkXLl5A1p7PJyMrGRiIQyh8GSjpU0",
    mapAbstract: "https://lh3.googleusercontent.com/aida-public/AB6AXuBu-GCTQnhmk1VDjpOpS9eAKOoNdSokAXQLy9KNt_K5Gv_ohB17KGnJcktaTFyj-T6tbwP17czzYWCUxrkrLwQvBKkSbGoP_O7MDZ90SczrOcGLhArHc5ugm_0RCoIxDTJw3cnyrt0nJCdLaCTF5ueQdWgWxGpimdLN84cln_ITrRN1bij2FY71X0kJLhQ1bU-4d2FcPeND_5Q3T0QZuSrmtbt8nxgkG-ytZoWBkYiJKwJXLbxKLZGO7yuGqNsAUQPn_JWkyjmU2IE",
    architecture: "https://lh3.googleusercontent.com/aida-public/AB6AXuCd4UW8uw0gnkz4Aa3mzfwWncC-mgun6sRKMoXeDwK6_sfVyc6RevKiIPoANajhN7W1tV-1zrNw82pjqqjL7U-9yNp458Al7U_LZA5fZ1NqXwEy_r4NxvhArJSaPj-LYUWnyT2JwVjKZIjO9A3B1Oe5fK7Pm5z5WfWvtNtSfi64DlvM1RDXjHZd-i4cTlCnXoNpi_alQrheAsFX9jgp11IwJqfnfTlZu06vM7PQb0fCaEjEIjNrPkD4wwYTs447PXYD_3sx7toRwmE",
    womanWalking: "https://lh3.googleusercontent.com/aida-public/AB6AXuDtoQCRmKbAPmdD0neqrblIKaD3dHR_Hk_v5sz3d8n863vVRwf12xjntNgEetUUEr0tj9QZSyBusVHx_VjGuzVwzXLtz4wRm0TqCT8Ns4Id_yF_cRgUdKLQesilEovgEfzsKTfbbZPypmCVuFU8fO3-JuvMB13W8djiZvqJhMZjrsCKTZIi2oDYd-WptOsIOhWXpKuoqZvcGlbbL5mYYbJsi2M59ipc1OnxM8gdOYmuJnj2IHELCz2TOVHkCug7zYCB2i5y_VsdIJs",
    clientNico: "https://lh3.googleusercontent.com/aida-public/AB6AXuAqp3cblT7pA3aS8e5jM9KxsRtlwRde7m0TKglcqNyIcLcsv_pfrsYtRqiSEPV2QWkAAWG1DafZnVd9vnx2l26JUspEcuDfFun-eNn99gpwYiEKthzltJhfxhwI6LCnmiFvkB79x-7dnI4PvOkIKAnk0dvUMD2-NWhBZ-K6GsXplsbujilJufomjEQnqzX_C_MJ4zp_pGQ_eHwALfd8Uqniurr-0o0-O7iMx2rMchdicjrRfvcXiFtfAqn7O_nuD1-QTNGTNGtTGeI",
    clientSofia: "https://lh3.googleusercontent.com/aida-public/AB6AXuCM1LNiClHT-8fq-gJmnrDctIyVcAJjjBeHpkSJ3Jh6dxiHbxlrTk_9BKFz-CXjlPYznaCn7vGftiOG_YOLKXD56MylDOJgVzGTPx571_r2IBCDuaFRpWhzdOGx2eoTuibuHFQXmC5wFgH2gW_JDQCc44DF6qbve7706p_rITeKkyKBu6CFk1kRxon2A9G1vugV1wMTMCqwybuyTbDKkxP-htHV-xLS9OQaDc2regoaFXbGeD_RMfxDDDuLcMnOcWNq11ASC9hWbOo",
    fabricTexture: "https://lh3.googleusercontent.com/aida-public/AB6AXuCXmGljGBl3v_Oo6aSerufQn0TqGJCblgxx770MSQ-6YPqxCEPYpeD3YAB9kslDdi-P3mnyTjDqYm-V6t-npqEUJnePHyZTfRaLUER3lsAjdb1rjvyHSPjPcDgR91WZMFRgjg66qiututaGjDvlcrXQWBTObYaDJSDXAOP7P7w9toMT_2cqBK5J0lnW6JGTaiysdZ1kugdwIbbe368ih8byRSeDiyqvZx9lLg7kLiJ2_x3QnN1ivzIp2Xazxkd8t3LmMsTaYBhuOcc",
    clientCami: "https://lh3.googleusercontent.com/aida-public/AB6AXuDmpV_oZmzyd3JuaF4DoJiltbmMt1l6zp--QzIn2ElgtFAkh1CWqJ7zdViJ4bXoL_mrYM2bs43svT-e5lH-D2WpQej0mDpRMkPGjT5Png-ISNMxBGRkhepQeIfm_desvX9_aEbEGANfh0-IC2GtninvcESEsXJVLyif76SmT42tq-wiDoLAMiFpPeGuOaEJterv8S3PE4Z-tS-Is97UOyXn_A6EaQ19udFZnkQZ388jRmuE0xpdrdQVVYkzEJQFejzr7Mty2XVOMpc",
    
    // Shop Specific
    dressFlow: "https://lh3.googleusercontent.com/aida-public/AB6AXuCimvnsy5LrWw8tc1MhSQQ1S9qmRbJX1iZSyrs5JYrtpLMdyUa2TK8syWbp_LtXYcPrhM4aKIxrqfXIIDwFvSlqnsnvBxO9Obq5X9Hhz87KxeDGzZARK_hUv0X6lN5DVfdaBJlBMGtor1msUY_6FTJDZDB0OXqK_qgreJ9I8w052kD-NCHeBmjNXpUylmAEaUwHnJar3Y9WhbYLO1VseZYaAkgvtv-Ypw6Hl913pOsMZBuMVq6NpBnfJw8W9YFpUt69ycv7BoMfi1Q",
    whiteTshirt: "https://lh3.googleusercontent.com/aida-public/AB6AXuBAW-NDXV9ghWWPRomEo085vK0cr8lGKoqKwrhXj2pBKM0lLwEC_7SA6fbkO3LGeBRqmM77b_SwgRhIK0gr64ClcoMCVC-2GiROhQtuwd3Rn2WpcGZ3a1yBLWkIPBjgQCxWwH-uitgFifpjJ2MWYN-EiWNBvE5KHKvBBu70lw7ErEHwk80R7mKN_awrBN6dCRYY8Lo_aabGzFalO0yQ1S70ArOsoT3VWQIAzFs4pR8z_wdqjICKteVi4T_SXulFDeEClX_6eOz6yZ8",
    videoThumb: "https://lh3.googleusercontent.com/aida-public/AB6AXuCEYNRNTvEV7SPA-nk2f0Yco7h6n95z82y9NVopOEYxX91bDRvmiAkGeJxc2l808lcm-aizGAulHKiZkVxXeRASTHqk-t1IJpOuZoFNGvSkmeUgiMTmYvmf_-hwfWjZGMRBFnRrIPhyJU5AwZzCpFQ1Q2F-tEnpFZXkPgNZJnuFCBV2SnLq_VmQ6atlC7YbHgM0xiMXjrv0xXr0U2VXOYjhC-M9g2uo1Wgo9gNqKAHvnYWM1hS1wOURGtoIdhvoobHhZl3YGa8GVgM",
    tieDyeHoodie: "https://lh3.googleusercontent.com/aida-public/AB6AXuAfGWnp5jDH_vv4yTeXzayx6Otc65AJ_K7YjbWkqcup22zapZRWdZ0MFMs1zMg1G2-NvYFuYdAwVVUycgZAjILYklkWixeyfTfBh14l0oeBlihPk3P8lvWScMnH84DHlVS7a6mtdyhd_xJSbkDx6fSJHIFieWfPp_a3JBoWQwJUjAzYupoERZKGvLNx9sJ3B0QApybP3-fW1gx1dYAV6NoYwzX1OBz_bB0sNUtVQzmQdrHrQEhNAWmt2Ce4boT1Go1IZauhVfrnzmY",
    beigeCoatMan: "https://lh3.googleusercontent.com/aida-public/AB6AXuB0J_8Ko7DFeLvLxrHIamRtSJuIQpljjM-rO6CNUa0YJOrAR06qG9-z8FQ6pVpzaAOf3Bl5CS0ztTcsDdHcsfEqfkEnX8lp2Pwd5NYIGywKIkzz12BPEWY_ZYQOEOwSYtIzPsR6zyAsSVDAGXGO6FZgiU1qS7PxMoqLNOJNNLvE9NbH0ls8BHpDFpm491DrQ2Wo7etrAFToKDLi3OcG8Bc8OFryNP4eiW6fpa-PLlwmLe2rlpEOJjocUhFFMJAI3aMW-rq2LW5w6IQ",
    sneakers: "https://lh3.googleusercontent.com/aida-public/AB6AXuBRV0SfAuc8saeCY6Bkw47mlKe8JZNddgYeajhfyu2kysQSMWyMvOhW09dif3AS7ZmDehdWqG1EVxFlLYT1wS8jqjouCHPkFnqJ2f9_WGgm1YvWrvpMEtxOGANUDoopWYwAAQ459Li3RieOEaDrVtYko8NBcKkd662WTUHGX9zlrjbxzkc5sW2sijoeh0stHctUJL3W5IMOaM_zWQnyJcDBgLE7l2agUtYLs_Lzust9wjA0sbR-dMAw-s_C1_a_WyUQIur5__ZjZdw",
    sunglasses: "https://lh3.googleusercontent.com/aida-public/AB6AXuA-HBFBBIfgj7mVkpy2B0V7HqDA87l5On5hocQxtgHzyU67_dS9K7cPxVyW49nJE9Ai8f4osqQ2JLcev5uM3OUtnnG3DCLsUUi2PCJWGEQLtUoYM6U3b7ZIop6WJ67YHsIBww4x_jylCQTzieF5dezQcE4-PjK0ySWtYNGo9tN6s2e8Rp7lnLaZgcJTuZHTR8EZbpZHjQW8jrzY5aOoLVm9hTg2PplbuQrEecMJYkdnCTnMU8xbTWqjn8VOMMl174O10D0YpQwTSP4",
    cargoPants: "https://lh3.googleusercontent.com/aida-public/AB6AXuCMY_T0P3mNwl9t0tDSBbgZnzB88p171w7_1-8Z_AW_G08hT74llyYTa-k1VmhG2dl5gCRdOIGaYH5bQoLLkDs2n-CFO8WyCopYJHG90TMQ5Knv31rM6OmFZUqIsUXWRFB0iLGRsW00gJF2cgI0uL005OxDbkp1ereAGE5i8BYEJYH5blHHzleoOsXy5-Vvq4_j0exMZC2SDb9VnyggiP_56cjxY6KHyViNgkn8I5z2UG0tfQrBGQopQQmWeQfWfcDNQLr0daV3SlM",
    accessories: "https://lh3.googleusercontent.com/aida-public/AB6AXuCA8vM5id3JfxfPa1e_GnhLMsdHIgLJSv7t2bS1-L1D9fd_dNdWEJ-dVQLU6GuxjFb7P9owrMaCTDcwRQxNv5HLOD-gL88ilyA3F5HeDq2QU5wE1-imYixVn4oQ09S-8foZfJJc7zXiXxFkg87opqzXPZbmcYxvtcRryze5JscWE_Xvfl9OWO0JKVgGaSseWpMvFDszIYbODz6u2RUqRYUxokVSECoNyIandE4b6UNAWLBVrHcvQ9sSNsE7SlVBvg7n_tndrUoeoE8",
    jeans: "https://lh3.googleusercontent.com/aida-public/AB6AXuDTvVitk7agKSVNSb13Nu58xyvGSGb2YrqM1-6ZcAd7p0Vw9Bjbuf56ofgRuhUIhU7NUZ5cYQ-rhOWRuVf53D0vYu8-jHyj-T7vRKdMqG-TCkcRuX_VDq9TPptEI1fVgulmciWIypCUe10tUXSy1jXKYlZx5i9QPg5lA_J7WBkWQUaxCugxJjRM9frfmRwzg0iL-cqiVkWuqxUJhjdyHae4qAVtwtFvXt3JhuUfxT2VxvoTvM0WyhEFBNQD2dmOqxh7gUDntLQJTyU",
    cap: "https://lh3.googleusercontent.com/aida-public/AB6AXuDeD3-db_AfLMoCwEedlBqWD75DoQ2443OQrIqiUaGWlmdjwup4Dy1pxMfy7Vtcma-daHBziFHEn5zNh8XoAiZL7W_71pjWq91AAfCJ11pnKvdM9MMr0WGYe4kjpuZn3flXsVlZUtGQH7ngqNH5BYj8WTa5qP_FlWJDWKxIuFZTKbgCCPgM4kIdEXKu7royvIDqzAT3UlnJrrdpaIRNjorM2P2g7JdvygSJZzwhZCR15GZKYZvy72QsyQLy9DuYvPvNpmqFfxgqXbg",
    friends: "https://lh3.googleusercontent.com/aida-public/AB6AXuBtIa_uNBTusPdzCbMwBUgkUrQqpNA2guLwuJpK7-99zcU0-E4AAOJqKes_kZDCGua78lxh1G5rMI-hMpb3d4G7D4OQqKNQryzIeJxgSGp6thvae4lyozCCHvG648Pja0HAlREelvhpPxAEi7wLzpoMt_TRkbUxSCdByUwvbR0mv0oH63BWHR_K3DWHg57SjCCOFCb_dCbq-8PryfNP8YZ_aw0dsp8v5iMvMont417b-35iljn4qmsMwrnoZ8A4qfmXYhByBylmZBA",
    packTshirts: "https://lh3.googleusercontent.com/aida-public/AB6AXuDgJmr6TmdpX9kdnz6myf5S7OFOKPIjZvBocXRaa_KcEa25l7aZaqJoQPhDC3X5vda9NTJS8Zfg4pFaLO97Zk_0n72WTjNpXjTXGQzbBURGPthpvwyNLyAM6M5J5fwI41RX2S6kGgeuMQgyUAIw57-Yd7TnHruEXUt3NYp2IipzElxiDVpUFauVWLOMJbwcovpDPzFwI91jDjYimKb0ALy3DM3nqN3M42sN3CUHBLcw9XSNtAQ2uUipcNH1A247khwS3AG9PBXWCgc"
};

export const MOCK_NEW_ARRIVALS: ProductItem[] = [
    { id: '1', title: 'Camisa de Lino Alvear', subtitle: 'Mezcla de Algodón', price: '$120', image: IMAGES.linenShirt, tag: { text: 'NUEVO', color: 'bg-primary' }, category: 'men', type: 'product' },
    { id: '2', title: 'Blazer Oversized Urbano', subtitle: 'Ajuste Estructurado', price: '$240', image: IMAGES.blazerOversized, category: 'women', type: 'product' },
    { id: '3', title: 'Chaqueta Denim Urbana', subtitle: 'Lavado Vintage', price: '$180', image: IMAGES.denimJacket, tag: { text: 'HOT', color: 'bg-orange-500' }, category: 'unisex', type: 'product' },
    { id: '4', title: 'Blusa de Seda Palermo', subtitle: '100% Seda Pura', price: '$150', image: IMAGES.silkBlouse, category: 'women', type: 'product' },
];

export const SHOP_ITEMS: Product[] = [
    { id: '1', type: 'product', title: 'Vestido Urban Flow', subtitle: 'Líneas simples', price: '$48.900', image: IMAGES.dressFlow, isNew: true, span: 'row-span-1', category: 'women' },
    { id: '2', type: 'product', title: 'Remera White Noise', subtitle: 'Algodón Premium', price: '$24.000', image: IMAGES.whiteTshirt, span: 'row-span-1', category: 'unisex' },
    { id: '3', type: 'video', title: 'CAMINANDO LA CIUDAD', image: IMAGES.videoThumb, span: 'row-span-2', live: true, category: 'unisex' },
    { id: '4', type: 'product', title: 'Campera Denim 90s', price: '$68.500', image: IMAGES.denimJacket, span: 'row-span-1', buttonLabel: 'Vista Rápida', category: 'unisex' },
    { id: '5', type: 'product', title: "Buzo Batik 'Storm'", price: '$58.000', image: IMAGES.tieDyeHoodie, span: 'row-span-1', tag: { text: 'TIE DYE', color: 'bg-accent text-slate-900' }, category: 'unisex' },
    { id: '6', type: 'product', title: 'Tapado Beige City', price: '$120.000', oldPrice: '$145.000', image: IMAGES.beigeCoatMan, span: 'row-span-1', category: 'men' },
    { id: '7', type: 'product', title: 'Street Runner V2', subtitle: 'Edición Limitada', price: '$85.000', image: IMAGES.sneakers, span: 'row-span-1', category: 'unisex' },
    { id: '8', type: 'product', title: 'Gafas Retro Black', subtitle: 'Accesorio Top', price: '$12.000', image: IMAGES.sunglasses, span: 'row-span-1', category: 'unisex' },
    { id: '9', type: 'banner', text: '"No es ropa, es actitud porteña."', author: 'TU MARCA TEAM', span: 'row-span-1', category: 'unisex' },
    { id: '10', type: 'product', title: "Buzo Oversize 'Vortex'", subtitle: 'Gris Melange', price: '$55.000', image: IMAGES.heroWoman, span: 'row-span-1', tag: { text: 'BEST SELLER', color: 'bg-black/60 text-white' }, category: 'women' },
    { id: '11', type: 'product', title: "Pantalón Wide Leg 'Flow'", price: '$46.000', image: IMAGES.cargoPants, span: 'row-span-1', hoverBorder: true, category: 'men' },
    { id: '12', type: 'look', title: 'Look Completo', image: IMAGES.accessories, span: 'row-span-2', category: 'unisex' },
    { id: '13', type: 'product', title: "Jean Relaxed '90s'", price: '$62.000', image: IMAGES.jeans, span: 'row-span-1', category: 'unisex' },
    { id: '14', type: 'flash', title: 'FLASH SALE', subtitle: 'Hasta 40% OFF', span: 'row-span-1', category: 'unisex' },
    { id: '15', type: 'product', title: "Gorra 'Midnight'", price: '$18.500', image: IMAGES.cap, span: 'row-span-1', category: 'unisex' },
    { id: '16', type: 'product', title: 'Cargo Táctico', subtitle: 'Verde Militar', price: '$42.000', image: IMAGES.cargoPants, span: 'row-span-1', category: 'men' },
    { id: '17', type: 'product', title: 'Pack 3 Básicas', price: '$45.000', image: IMAGES.packTshirts, span: 'row-span-1', category: 'men' },
    { id: '18', type: 'product', title: 'Camisa Lino', subtitle: 'Relaxed Fit', price: '$75.000', image: IMAGES.linenShirt, span: 'row-span-1', category: 'men' },
    { id: '19', type: 'product', title: 'Chaqueta Bomber', subtitle: 'Nylon Negro', price: '$89.900', image: IMAGES.denimJacket, span: 'row-span-1', category: 'men', tag: { text: 'NUEVO', color: 'bg-primary' } },
    { id: '20', type: 'product', title: 'Bermuda Cargo', subtitle: 'Ripstop', price: '$35.000', image: IMAGES.cargoPants, span: 'row-span-1', category: 'men' },
    { id: '21', type: 'product', title: 'Hoodie Essential', subtitle: 'Negro Liso', price: '$52.000', image: IMAGES.whiteTshirt, span: 'row-span-1', category: 'men' },
    { id: '22', type: 'product', title: 'Jean Carpenter', subtitle: 'Denim Crudo', price: '$65.000', image: IMAGES.jeans, span: 'row-span-1', category: 'men' },
    { id: '23', type: 'product', title: 'Camisa Oversize', subtitle: 'Rayas Azules', price: '$48.000', image: IMAGES.linenShirt, span: 'row-span-1', category: 'men' },
    { id: '24', type: 'banner', text: '"Estilo sin esfuerzo para el hombre moderno."', author: 'MEN COLLECTION', span: 'row-span-1', category: 'men' },
];
